apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hot
  template:
    metadata:
      labels:
        app: hot
    spec:
      containers:
      - image: okteto.dev/hot:latest
        name: hot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f97615e4-8ab1-4dbd-8c16-61499d2bb140"
        - name: Vless_Path
          value: "/bde6t7dne7guygffdyy45st"
        - name: Vmess_UUID
          value: "f97615e4-8ab1-4dbd-8c16-61499d2bb140"
        - name: Vmess_Path
          value: "/bde6t7dne7guygffdyy45st"
        - name: Share_Path
          value: "/v2link"
